In [48]:
import numpy as np

In [50]:
l = np.array([[1, 2, 3],
             [4, 5, 6]])
l.shape

(2, 3)

In [53]:
l + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
l + np.array([[5, 5, 5],
             [5, 5, 5]])

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
l * 2 

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [55]:
l * np.array([[2, 2, 2],
             [2, 2, 2]])

array([[ 2,  4,  6],
       [ 8, 10, 12]])